export type SeedCategory = {
  id: string;
  name: string;
  icon: string;
  color: string;
  kind: 'expense' | 'income';
  keywords: string[];
};

/**
 * Seed categories double as the parser's dictionary.
 *
 * Keywords are the *things people buy*, not just category names — "face wash"
 * and "curd" are what actually gets typed, and matching only on "toiletries" or
 * "groceries" is why those fell through to Other. Merchant names matter for the
 * same reason: a shop name is often the only word in the line.
 */
export const SEED_CATEGORIES: SeedCategory[] = [
  {
    id: 'food',
    name: 'Food & Drink',
    icon: 'utensils',
    color: '#FF6B57',
    kind: 'expense',
    keywords: [
      'food', 'lunch', 'dinner', 'breakfast', 'brunch', 'snack', 'snacks', 'meal', 'meals',
      'eat', 'eating', 'ate', 'restaurant', 'cafe', 'canteen', 'mess', 'tiffin', 'takeaway',
      'takeout', 'bento',
      'pizza', 'burger', 'biryani', 'dosa', 'idli', 'samosa', 'roll', 'shawarma', 'sandwich',
      'noodles', 'ramen', 'udon', 'soba', 'sushi', 'sashimi', 'donburi', 'gyudon', 'katsu',
      'tempura', 'curry', 'onigiri', 'gyoza', 'yakitori', 'okonomiyaki', 'takoyaki',
      'salad', 'soup', 'pasta', 'fried chicken', 'karaage',
      'coffee', 'tea', 'chai', 'juice', 'shake', 'smoothie', 'latte', 'espresso', 'matcha',
      'beer', 'wine', 'sake', 'highball', 'chuhai', 'drinks', 'bar', 'izakaya', 'nomikai',
      'soda', 'cola',
      'icecream', 'ice cream', 'dessert', 'cake', 'sweets', 'bakery', 'donut', 'pudding', 'crepe',
      'swiggy', 'zomato', 'zom', 'dominos', 'kfc', 'mcdonalds', 'mcd', 'subway', 'starbucks',
      'ccd', 'chaipoint', 'ubereats',
      'saizeriya', 'saizeria', 'sukiya', 'yoshinoya', 'matsuya', 'ichiran', 'coco ichibanya',
      'cocoichi', 'sushiro', 'kura sushi', 'hamazushi', 'mos burger', 'mosburger', 'freshness',
      'ootoya', 'tenya', 'gusto', 'jonathans', 'dennys', 'ringer hut', 'ippudo',
      'doutor', 'tullys', 'komeda', 'excelsior', 'veloce', 'st marc', 'mister donut', 'misdo',
      'baskin robbins', 'krispy kreme', 'lotteria', 'first kitchen',
    ],
  },
  {
    id: 'groceries',
    name: 'Groceries',
    icon: 'cart',
    color: '#34D399',
    kind: 'expense',
    keywords: [
      'grocery', 'groceries', 'supermarket', 'kirana', 'provision', 'ration', 'market',
      'vegetables', 'veggies', 'sabzi', 'fruits', 'fruit', 'milk', 'bread', 'eggs', 'egg',
      'rice', 'atta', 'flour', 'dal', 'lentils', 'oil', 'sugar', 'salt', 'spices', 'masala',
      'curd', 'yogurt', 'yoghurt', 'cheese', 'butter', 'paneer', 'tofu', 'natto', 'miso',
      'soy sauce', 'cereal', 'oats', 'honey', 'jam', 'ketchup',
      'chicken', 'meat', 'beef', 'pork', 'fish', 'seafood', 'prawns', 'frozen food',
      'onion', 'potato', 'tomato', 'banana', 'apple', 'orange', 'grapes',
      'lawson', 'familymart', 'family mart', 'famima', '7-eleven', 'seven eleven',
      'seveneleven', '7eleven', 'ministop', 'seicomart', 'daily yamazaki', 'combini', 'konbini',
      'gyoumu', 'gyomu', 'gyomu super', 'gyoumu super', 'gyomusuper', 'giyoumu', 'ok store',
      'okstore', 'maruetsu', 'summit', 'aeon', 'ito yokado', 'seiyu', 'life super', 'hanamasa',
      'inageya', 'yaoko', 'tokyu store', 'kaldi',
      'bigbasket', 'blinkit', 'zepto', 'instamart', 'dmart', 'd mart', 'reliance fresh',
      'grofers', 'jiomart',
    ],
  },
  {
    id: 'toiletries',
    name: 'Toiletries',
    icon: 'droplet',
    color: '#22D3EE',
    kind: 'expense',
    keywords: [
      'しゃんぷー', 'りんす', 'こんでぃしょなー', 'ぼでぃそーぷ', 'せっけん', '石鹸',
      'はみがき', '歯磨き', 'はぶらし', '歯ブラシ', 'せんがん', '洗顔', 'けしょうすい',
      '化粧水', 'かみそり', 'ひげそり', 'おむつ', 'なぷきん', 'にゅうえき', 'にきび',
      'toiletries', 'face wash', 'facewash', 'body wash', 'bodywash', 'shower gel', 'soap',
      'shampoo', 'conditioner', 'hair oil', 'toothpaste', 'toothbrush', 'mouthwash', 'floss',
      'razor', 'shaving', 'shaving cream', 'deodorant', 'perfume', 'body lotion', 'lotion',
      'moisturizer', 'moisturiser', 'face cream', 'sunscreen', 'sunblock', 'lip balm',
      'cotton', 'tissue', 'tissues', 'toilet paper', 'wet wipes', 'wipes', 'sanitizer',
      'sanitary pads', 'tampons', 'diaper', 'diapers', 'nail cutter', 'hair gel',
      'face mask', 'serum', 'toner', 'cleanser', 'skincare', 'cosmetics', 'makeup',
      'matsumoto kiyoshi', 'matsumoto', 'matsukiyo', 'kiyoshi', 'kyoshi', 'kyoushi',
      'welcia', 'sugi', 'tsuruha', 'cosmos', 'sundrug', 'sun drug', 'create sd', 'kokumin',
      'drugstore', 'drug store', 'nykaa', 'purplle',
    ],
  },
  {
    id: 'household',
    name: 'Household',
    icon: 'house',
    color: '#C0895A',
    kind: 'expense',
    keywords: [
      'せんざい', '洗剤', 'せんたく', '洗濯', 'じゅうなんざい', '柔軟剤', 'ごみぶくろ',
      'ゴミ袋', 'てぃっしゅ', 'といれっとぺーぱー', 'きっちんぺーぱー', 'らっぷ',
      'あるみほいる', 'でんち', '電池', 'そうじ', '掃除', 'しょっき', '食器',
      'household', 'detergent', 'laundry liquid', 'fabric softener', 'dish soap', 'dishwash',
      'cleaner', 'cleaning', 'bleach', 'sponge', 'garbage bag', 'trash bag', 'bin bag',
      'kitchen', 'utensils', 'plates', 'cups', 'cutlery', 'pan', 'pot', 'storage box',
      'hanger', 'hangers', 'bulb', 'battery', 'batteries', 'extension cord', 'furniture',
      'mattress', 'bedsheet', 'pillow', 'blanket', 'curtain', 'towel', 'doormat', 'decor',
      'nitori', 'ikea', 'daiso', 'seria', 'can do', 'cando', 'don quijote', 'donki',
      'homecenter', 'home center', 'cainz', 'komeri',
    ],
  },
  {
    id: 'transport',
    name: 'Transport',
    icon: 'taxi',
    color: '#38BDF8',
    kind: 'expense',
    keywords: [
      'transport', 'auto', 'rickshaw', 'cab', 'taxi', 'uber', 'ola', 'rapido', 'bus',
      'metro', 'train', 'ticket', 'railway', 'irctc', 'toll', 'parking', 'commute', 'ride',
      'fare', 'namma yatri', 'blusmart', 'bike taxi',
      'jr', 'jr pass', 'suica', 'pasmo', 'icoca', 'shinkansen', 'toei', 'keio', 'odakyu',
      'tobu', 'seibu', 'keikyu', 'tokyu', 'yamanote', 'metro pass', 'teiki', 'commuter pass',
      'ic charge', 'charge suica', 'charge pasmo',
    ],
  },
  {
    id: 'fuel',
    name: 'Fuel',
    icon: 'fuel',
    color: '#FB923C',
    kind: 'expense',
    keywords: ['fuel', 'petrol', 'diesel', 'gasoline', 'gas station', 'cng', 'refuel', 'eneos', 'idemitsu', 'bunk'],
  },
  {
    id: 'bills',
    name: 'Bills & Utilities',
    icon: 'bulb',
    color: '#818CF8',
    kind: 'expense',
    keywords: [
      'bill', 'bills', 'utility', 'utilities', 'electricity', 'current bill', 'current gas',
      'power', 'denki', 'water', 'suido', 'water bill', 'gas bill', 'gas', 'city gas',
      'cylinder', 'lpg', 'maintenance', 'society', 'nhk', 'tepco', 'tokyo gas', 'kepco',
    ],
  },
  {
    id: 'mobile',
    name: 'Phone & Internet',
    icon: 'wifi',
    color: '#0EA5E9',
    kind: 'expense',
    keywords: [
      'internet', 'wifi', 'broadband', 'fiber', 'phone bill', 'mobile bill', 'recharge',
      'data pack', 'sim', 'docomo', 'au', 'softbank', 'rakuten mobile', 'ymobile', 'y mobile',
      'uq mobile', 'ahamo', 'povo', 'linemo', 'nuro', 'airtel', 'jio', 'vi', 'vodafone',
      'bsnl', 'dth', 'cable',
    ],
  },
  {
    id: 'rent',
    name: 'Rent & Housing',
    icon: 'building',
    color: '#A855F7',
    kind: 'expense',
    keywords: [
      'rent', 'house rent', 'room rent', 'yachin', 'pg', 'hostel', 'deposit', 'landlord',
      'lease', 'shikikin', 'reikin', 'key money', 'renewal fee', 'management fee', 'apartment',
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'bag',
    color: '#E879F9',
    kind: 'expense',
    keywords: [
      'shopping', 'bought', 'purchase', 'bag', 'watch', 'accessories', 'sunglasses', 'wallet',
      'jewellery', 'jewelry', 'amazon', 'rakuten', 'mercari', 'flipkart', 'myntra', 'ajio',
      'meesho', 'shein', 'temu', 'yahoo shopping',
    ],
  },
  {
    id: 'clothing',
    name: 'Clothing',
    icon: 'shirt',
    color: '#F472B6',
    kind: 'expense',
    keywords: [
      'clothes', 'clothing', 'shirt', 'tshirt', 't-shirt', 'jeans', 'trousers', 'pants',
      'jacket', 'coat', 'hoodie', 'sweater', 'dress', 'skirt', 'socks', 'innerwear',
      'underwear', 'shoes', 'sneakers', 'sandals', 'boots', 'cap', 'belt', 'scarf',
      'uniqlo', 'gu', 'muji', 'zara', 'shimamura', 'workman', 'abc mart',
    ],
  },
  {
    id: 'electronics',
    name: 'Electronics',
    icon: 'phone',
    color: '#7C3AED',
    kind: 'expense',
    keywords: [
      'electronics', 'gadget', 'mobile phone', 'smartphone', 'laptop', 'tablet', 'ipad',
      'headphones', 'earphones', 'earbuds', 'airpods', 'charger', 'power bank', 'keyboard',
      'mouse', 'monitor', 'ssd', 'hard disk', 'memory card', 'camera', 'printer',
      'yodobashi', 'bic camera', 'biccamera', 'yamada denki', 'edion', 'kojima', 'apple store',
    ],
  },
  {
    id: 'health',
    name: 'Health & Medical',
    icon: 'stethoscope',
    color: '#2DD4BF',
    kind: 'expense',
    keywords: [
      'health', 'medical', 'medicine', 'medicines', 'meds', 'tablets', 'pharmacy', 'chemist',
      'doctor', 'clinic', 'hospital', 'checkup', 'blood test', 'lab', 'scan', 'x-ray',
      'dentist', 'dental', 'therapy', 'counselling', 'surgery', 'vaccine', 'injection',
      'physio', 'eye test', 'spectacles', 'glasses', 'contact lens', 'painkiller',
      'byouin', 'apollo', 'pharmeasy', '1mg', 'netmeds',
    ],
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'dumbbell',
    color: '#4ADE80',
    kind: 'expense',
    keywords: [
      'gym', 'fitness', 'workout', 'yoga', 'pilates', 'swimming', 'sports', 'protein',
      'supplements', 'trainer', 'anytime fitness', 'chocozap', 'sports club',
    ],
  },
  {
    id: 'personal',
    name: 'Personal Care',
    icon: 'scissors',
    color: '#FB7185',
    kind: 'expense',
    keywords: [
      'salon', 'haircut', 'hair', 'barber', 'spa', 'massage', 'grooming', 'beauty', 'parlour',
      'parlor', 'nail', 'manicure', 'pedicure', 'facial', 'waxing', 'laundry', 'dry clean',
      'ironing', 'qb house', 'qbhouse', 'coin laundry',
    ],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: 'film',
    color: '#F43F5E',
    kind: 'expense',
    keywords: [
      'entertainment', 'movie', 'movies', 'cinema', 'pvr', 'inox', 'bookmyshow', 'toho cinemas',
      'concert', 'gig', 'show', 'event', 'game', 'games', 'gaming', 'arcade', 'karaoke',
      'outing', 'party', 'club', 'bowling', 'zoo', 'museum', 'aquarium', 'theme park',
      'disney', 'usj', 'pachinko', 'book', 'books', 'manga', 'comic',
    ],
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    icon: 'repeat',
    color: '#A78BFA',
    kind: 'expense',
    keywords: [
      'subscription', 'subscriptions', 'membership', 'renewal', 'saas',
      'netflix', 'prime', 'amazon prime', 'spotify', 'youtube premium', 'youtube', 'hotstar',
      'jiocinema', 'sony liv', 'zee5', 'disney plus', 'hulu', 'abema', 'unext', 'dazn',
      'icloud', 'google one', 'dropbox', 'chatgpt', 'openai', 'claude', 'anthropic',
      'ai subscription', 'copilot', 'midjourney', 'notion', 'canva', 'adobe', 'figma',
      'github', 'apple music', 'kindle unlimited', 'audible',
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Tour',
    icon: 'plane',
    color: '#06B6D4',
    kind: 'expense',
    keywords: [
      'travel', 'tour', 'trip', 'flight', 'flights', 'airfare', 'airport', 'holiday',
      'vacation', 'hotel', 'stay', 'resort', 'ryokan', 'airbnb', 'oyo',
      'makemytrip', 'goibibo', 'booking', 'agoda', 'expedia', 'jalan', 'rakuten travel',
      'visa fee', 'passport', 'sightseeing', 'tourism', 'excursion', 'road trip', 'luggage',
      'souvenir', 'omiyage',
    ],
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'cap',
    color: '#A3E635',
    kind: 'expense',
    keywords: [
      'education', 'course', 'courses', 'class', 'classes', 'tuition', 'fees', 'fee',
      'college', 'school', 'university', 'exam', 'textbook', 'textbooks', 'stationery',
      'notebook', 'pen', 'udemy', 'coursera', 'certification', 'training', 'coaching',
      'japanese class', 'jlpt', 'language school',
    ],
  },
  {
    id: 'work',
    name: 'Work Expenses',
    icon: 'briefcase',
    color: '#F59E0B',
    kind: 'expense',
    keywords: [
      'work expense', 'office', 'business trip', 'coworking', 'printing', 'business card',
      'meishi', 'conference', 'seminar', 'team lunch',
    ],
  },
  {
    id: 'gifts',
    name: 'Gifts & Donations',
    icon: 'gift',
    color: '#EF4444',
    kind: 'expense',
    keywords: [
      'gift', 'gifts', 'present', 'donation', 'donate', 'charity', 'temple', 'church',
      'mosque', 'offering', 'wedding gift', 'birthday gift', 'tip', 'shagun', 'goshugi',
      'otoshidama', 'flowers',
    ],
  },
  {
    id: 'family',
    name: 'Family & Kids',
    icon: 'users',
    color: '#FBBF24',
    kind: 'expense',
    keywords: [
      'family', 'kids', 'children', 'child', 'baby', 'toys', 'toy', 'stroller', 'daycare',
      'nursery', 'wife', 'husband', 'partner', 'pocket money', 'helper', 'maid', 'babysitter',
    ],
  },
  {
    id: 'parents',
    name: 'Family Support',
    icon: 'heart',
    color: '#EC4899',
    kind: 'expense',
    keywords: [
      'sent parents', 'sent to parents', 'parents', 'mom', 'mother', 'dad', 'father', 'amma',
      'appa', 'home money', 'sent home', 'family support', 'remittance', 'send home',
      'money to parents', 'support family', 'transfer home',
    ],
  },
  {
    id: 'pets',
    name: 'Pets',
    icon: 'dog',
    color: '#F97316',
    kind: 'expense',
    keywords: ['pet', 'pets', 'dog', 'cat', 'pet food', 'dog food', 'cat food', 'vet', 'litter'],
  },
  {
    id: 'insurance',
    name: 'Insurance',
    icon: 'star',
    color: '#6366F1',
    kind: 'expense',
    keywords: ['insurance', 'premium', 'lic', 'health insurance', 'life insurance', 'car insurance', 'hoken'],
  },
  {
    id: 'taxes',
    name: 'Taxes & Fees',
    icon: 'receipt',
    color: '#B45309',
    kind: 'expense',
    keywords: [
      'tax', 'taxes', 'income tax', 'residence tax', 'juminzei', 'nenkin', 'pension',
      'fine', 'penalty', 'challan', 'late fee', 'bank charge', 'service charge', 'atm fee',
      'transfer fee',
    ],
  },
  {
    id: 'unexpected',
    name: 'Unexpected',
    icon: 'alert',
    color: '#FACC15',
    kind: 'expense',
    keywords: [
      'unexpected', 'emergency', 'repair', 'repairs', 'damage', 'breakdown', 'replacement',
      'urgent', 'accident', 'servicing', 'puncture', 'mechanic', 'plumber', 'electrician',
      'locksmith',
    ],
  },
  {
    id: 'investments',
    name: 'Investments & Savings',
    icon: 'trending',
    color: '#10B981',
    kind: 'expense',
    keywords: [
      'investment', 'invest', 'sip', 'mutual fund', 'mf', 'stocks', 'shares', 'equity',
      'gold', 'fd', 'rd', 'ppf', 'nps', 'crypto', 'bitcoin', 'savings', 'nisa', 'ideco',
      'zerodha', 'groww', 'upstox',
    ],
  },
  {
    id: 'loan',
    name: 'Loan & EMI',
    icon: 'bank',
    color: '#8B5CF6',
    kind: 'expense',
    keywords: [
      'loan', 'emi', 'installment', 'instalment', 'credit card bill', 'repayment',
      'interest paid', 'home loan', 'car loan', 'education loan', 'shakkin',
    ],
  },
  {
    id: 'lending',
    name: 'Lending & Borrowing',
    icon: 'undo',
    color: '#FDBA74',
    kind: 'expense',
    keywords: [
      'lent', 'lend', 'loan to a friend', 'loan to friend', 'lent to friend', 'gave friend',
      'loan friend', 'friend loan', 'lent friend', 'borrowed friend', 'paid friend',
      'loan from friend', 'loan friend money',
      'borrowed', 'borrow', 'paid back', 'returned money', 'settle up', 'owe', 'owed',
      'friend money', 'split bill', 'shared bill', 'friend',
    ],
  },
  {
    id: 'other',
    name: 'Other',
    icon: 'package',
    color: '#94A3B8',
    kind: 'expense',
    keywords: ['other', 'misc', 'miscellaneous', 'random', 'general', 'uncategorised', 'uncategorized'],
  },

  /* ------------------------------- income ------------------------------- */
  {
    id: 'salary',
    name: 'Salary',
    icon: 'wallet',
    color: '#22C55E',
    kind: 'income',
    keywords: ['salary', 'sal', 'paycheck', 'pay', 'stipend', 'wages', 'monthly salary', 'kyuuryou'],
  },
  {
    id: 'freelance',
    name: 'Freelance & Business',
    icon: 'briefcase',
    color: '#3B82F6',
    kind: 'income',
    keywords: ['freelance', 'freelancing', 'client payment', 'project payment', 'business', 'sales', 'profit', 'consulting', 'gig', 'side income'],
  },
  {
    id: 'returns',
    name: 'Interest & Returns',
    icon: 'coins',
    color: '#EAB308',
    kind: 'income',
    keywords: ['interest', 'dividend', 'returns', 'matured', 'capital gain', 'cashback', 'reward', 'points'],
  },
  {
    id: 'reimbursement',
    name: 'Reimbursements',
    icon: 'undo',
    color: '#14B8A6',
    kind: 'income',
    keywords: ['reimbursed', 'reimbursement', 'claim settled', 'expense claim', 'company paid back', 'got back', 'money returned'],
  },
  {
    id: 'refund',
    name: 'Refunds',
    icon: 'undo',
    color: '#84CC16',
    kind: 'income',
    keywords: ['refund', 'refunded', 'cancelled order', 'chargeback'],
  },
  {
    id: 'other_income',
    name: 'Other Income',
    icon: 'sparkles',
    color: '#BA68C8',
    kind: 'income',
    keywords: ['other income', 'gift received', 'prize', 'won', 'received', 'credited', 'income', 'furusato'],
  },
];

export const SEED_ACCOUNTS = [
  { id: 'cash', name: 'Cash', kind: 'cash', icon: 'note' },
  { id: 'bank', name: 'Bank', kind: 'bank', icon: 'bank' },
  { id: 'card', name: 'Card', kind: 'card', icon: 'card' },
  { id: 'wallet', name: 'Wallet / IC', kind: 'wallet', icon: 'wallet' },
];

/** Payment-method words the parser strips out of a line. */
export const METHOD_WORDS: Record<string, string> = {
  cash: 'Cash',
  upi: 'UPI',
  gpay: 'UPI',
  'google pay': 'UPI',
  phonepe: 'UPI',
  paytm: 'UPI',
  bhim: 'UPI',
  card: 'Card',
  'credit card': 'Card',
  'debit card': 'Card',
  cc: 'Card',
  netbanking: 'Bank',
  'net banking': 'Bank',
  bank: 'Bank',
  neft: 'Bank',
  imps: 'Bank',
  wallet: 'Wallet',
  paypay: 'Wallet',
  'rakuten pay': 'Wallet',
  'line pay': 'Wallet',
};
